dataset:
  name: "3RScan"
  base_dir: ./datasets/3RScan
  sequence: "1d2f8514-d757-207c-8e40-377957df6f67/sequence"
  start: 0
  end: -1
  stride: 3
  desired_height: 540
  desired_width: 960
  camera_params:
    image_height: 540
    image_width: 960
    fx: 756.832
    fy: 756.026
    cx: 492.889
    cy: 270.419
    png_depth_scale: 1000.0
    crop_edge: 0
  relative_pose: False
  device: "cpu"

nodes_constructor:
  mask_generator:
    model: "MobileSAM"
    weights_path: "/data/coding/sam_weight/"
  dino_generator:
    model: "dinov2_vits14_reg_lc"
    load_size: 448
    stride: 7
    facet: "value"
    num_patches_h: 63
    num_patches_w: 85
  detections_assembler:
    mask_conf_threshold: 0.95
    mask_area_threshold: 500
    max_bbox_area_ratio: 0.75
    min_points_threshold: 150
    downsample_voxel_size: 0.025
    dbscan_remove_noise: True
    dbscan_eps: 0.05
    dbscan_min_points: 10 
    image_area: 518400 # desired_height * desired_width
  objects_associator:
    merge_det_obj_spatial_sim_thresh: 0.01
    merge_det_obj_visual_sim_thresh: 0.5
    downsample_voxel_size: 0.025
    merge_interval: 20
    merge_objects_overlap_thresh: 0.7
    merge_objects_visual_sim_thresh: 0.4
  projector:
    num_views: 5
    top_k: 1
    desired_height: 540
    desired_width: 960
  postprocessing:
    obj_min_points: 300
    obj_min_detections: 5
  output_path: "./output/scenes"
  output_name_nodes: "3rscan_1d2f8514-d757-207c-8e40-377957df6f67.json"
  output_name_objects: "3rscan_1d2f8514-d757-207c-8e40-377957df6f67_00_objects.pkl.gz"
